### ISSUE TITLE
Universal cache strategy

### ISSUE THREAD

**Issue by ai** [code42day/postcss-cachify#1]
Mayb you should accept option with a function to set other place for cachebuster?

``` js
postcss([ require('postcss-cachify')({
    set: function (file) {
        return file.path.replace(/\.\w+$/, file.md5() + '$0');
    }
}) ])
```

**Comment by pirxpilot** [comment]
Maybe. However there are other postcss plugins that _kind of/sort of_ let you do that - for example [postcss-assets](https://github.com/borodean/postcss-assets). The problem is they are also doing whole bunch of other things. And I wrote this one to make it work specifically with [connect-cachify-static](https://github.com/borodean/postcss-assets) because that's I need - that's what I needed yesterday TBH ;-)
That said: patches always welcomed and if we end up with something more flexible it'll be great.

**Comment by ai** [comment]
So, why you didn’t use postcss-assets? :) Very strange to have special PostCSS plugin for every middleware ;).

**Comment by pirxpilot** [comment]
Two reasons:
- have a strong (possibly unjustified) preference for plugins that do one thing and one thing only
- needed a module that would tie connect-cachify-static and postcss-some-other-plugin together anyway

Also I think that **everybody** should just use connect-cachify-static for everything so that we can all live with just one plugin - j/k. Seriously though - should I even add it to postcss Readme? I didn't think I should - but then you opened this issue ;-)

**Comment by ai** [comment]
I agree with you, this is very specific plugin right now, so it will e better t find it from `connect-cachify-static` repo.
